site_name: C++ Korea Code of Conducts
site_url: https://cppkorea.github.io/codeofconduct

repo_name: cppkorea/codeofconduct
repo_url: https://github.com/cppkorea/codeofconduct

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

theme:
  name: "material"
  extra:
    search:
      language: "en, kr"
  # font:
  #   text: "Nanum Gothic"
  #   code: "Nanum Gothic Coding"
  palette:
    primary: "blue grey"
    accent: "blue"
  logo:
    icon: "call_split"
  # feature:
  #   tabs: true

extra:
  social:
    - type: "github"
      link: "https://github.com/cppkorea"
